//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.16 at 09:51:18 PM IST 
//


package xmlUtils.jdpa;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the xmlUtils.jdpa package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: xmlUtils.jdpa
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Annotations }
     * 
     */
    public Annotations createAnnotations() {
        return new Annotations();
    }

    /**
     * Create an instance of {@link Annotations.StringSlotMention }
     * 
     */
    public Annotations.StringSlotMention createAnnotationsStringSlotMention() {
        return new Annotations.StringSlotMention();
    }

    /**
     * Create an instance of {@link Annotations.ComplexSlotMention }
     * 
     */
    public Annotations.ComplexSlotMention createAnnotationsComplexSlotMention() {
        return new Annotations.ComplexSlotMention();
    }

    /**
     * Create an instance of {@link Annotations.ClassMention }
     * 
     */
    public Annotations.ClassMention createAnnotationsClassMention() {
        return new Annotations.ClassMention();
    }

    /**
     * Create an instance of {@link Annotations.Annotation }
     * 
     */
    public Annotations.Annotation createAnnotationsAnnotation() {
        return new Annotations.Annotation();
    }

    /**
     * Create an instance of {@link Annotations.StringSlotMention.MentionSlot }
     * 
     */
    public Annotations.StringSlotMention.MentionSlot createAnnotationsStringSlotMentionMentionSlot() {
        return new Annotations.StringSlotMention.MentionSlot();
    }

    /**
     * Create an instance of {@link Annotations.StringSlotMention.StringSlotMentionValue }
     * 
     */
    public Annotations.StringSlotMention.StringSlotMentionValue createAnnotationsStringSlotMentionStringSlotMentionValue() {
        return new Annotations.StringSlotMention.StringSlotMentionValue();
    }

    /**
     * Create an instance of {@link Annotations.StringSlotMention.ComplexSlotMentionValue }
     * 
     */
    public Annotations.StringSlotMention.ComplexSlotMentionValue createAnnotationsStringSlotMentionComplexSlotMentionValue() {
        return new Annotations.StringSlotMention.ComplexSlotMentionValue();
    }

    /**
     * Create an instance of {@link Annotations.ComplexSlotMention.MentionSlot }
     * 
     */
    public Annotations.ComplexSlotMention.MentionSlot createAnnotationsComplexSlotMentionMentionSlot() {
        return new Annotations.ComplexSlotMention.MentionSlot();
    }

    /**
     * Create an instance of {@link Annotations.ComplexSlotMention.ComplexSlotMentionValue }
     * 
     */
    public Annotations.ComplexSlotMention.ComplexSlotMentionValue createAnnotationsComplexSlotMentionComplexSlotMentionValue() {
        return new Annotations.ComplexSlotMention.ComplexSlotMentionValue();
    }

    /**
     * Create an instance of {@link Annotations.ClassMention.MentionClass }
     * 
     */
    public Annotations.ClassMention.MentionClass createAnnotationsClassMentionMentionClass() {
        return new Annotations.ClassMention.MentionClass();
    }

    /**
     * Create an instance of {@link Annotations.ClassMention.HasSlotMention }
     * 
     */
    public Annotations.ClassMention.HasSlotMention createAnnotationsClassMentionHasSlotMention() {
        return new Annotations.ClassMention.HasSlotMention();
    }

    /**
     * Create an instance of {@link Annotations.ClassMention.Mention }
     * 
     */
    public Annotations.ClassMention.Mention createAnnotationsClassMentionMention() {
        return new Annotations.ClassMention.Mention();
    }

    /**
     * Create an instance of {@link Annotations.ClassMention.Annotator }
     * 
     */
    public Annotations.ClassMention.Annotator createAnnotationsClassMentionAnnotator() {
        return new Annotations.ClassMention.Annotator();
    }

    /**
     * Create an instance of {@link Annotations.ClassMention.Span }
     * 
     */
    public Annotations.ClassMention.Span createAnnotationsClassMentionSpan() {
        return new Annotations.ClassMention.Span();
    }

    /**
     * Create an instance of {@link Annotations.Annotation.Mention }
     * 
     */
    public Annotations.Annotation.Mention createAnnotationsAnnotationMention() {
        return new Annotations.Annotation.Mention();
    }

    /**
     * Create an instance of {@link Annotations.Annotation.Annotator }
     * 
     */
    public Annotations.Annotation.Annotator createAnnotationsAnnotationAnnotator() {
        return new Annotations.Annotation.Annotator();
    }

    /**
     * Create an instance of {@link Annotations.Annotation.Span }
     * 
     */
    public Annotations.Annotation.Span createAnnotationsAnnotationSpan() {
        return new Annotations.Annotation.Span();
    }

}
