//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.16 at 09:52:44 PM IST 
//


package xmlUtils.stanford;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the xmlUtils.stanford package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: xmlUtils.stanford
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Root }
     * 
     */
    public Root createRoot() {
        return new Root();
    }

    /**
     * Create an instance of {@link Root.Document }
     * 
     */
    public Root.Document createRootDocument() {
        return new Root.Document();
    }

    /**
     * Create an instance of {@link Root.Document.Sentences }
     * 
     */
    public Root.Document.Sentences createRootDocumentSentences() {
        return new Root.Document.Sentences();
    }

    /**
     * Create an instance of {@link Root.Document.Sentences.Sentence }
     * 
     */
    public Root.Document.Sentences.Sentence createRootDocumentSentencesSentence() {
        return new Root.Document.Sentences.Sentence();
    }

    /**
     * Create an instance of {@link Root.Document.Sentences.Sentence.Dependencies }
     * 
     */
    public Root.Document.Sentences.Sentence.Dependencies createRootDocumentSentencesSentenceDependencies() {
        return new Root.Document.Sentences.Sentence.Dependencies();
    }

    /**
     * Create an instance of {@link Root.Document.Sentences.Sentence.Dependencies.Dep }
     * 
     */
    public Root.Document.Sentences.Sentence.Dependencies.Dep createRootDocumentSentencesSentenceDependenciesDep() {
        return new Root.Document.Sentences.Sentence.Dependencies.Dep();
    }

    /**
     * Create an instance of {@link Root.Document.Sentences.Sentence.Tokens }
     * 
     */
    public Root.Document.Sentences.Sentence.Tokens createRootDocumentSentencesSentenceTokens() {
        return new Root.Document.Sentences.Sentence.Tokens();
    }

    /**
     * Create an instance of {@link Root.Document.Sentences.Sentence.Dependencies.Dep.Governor }
     * 
     */
    public Root.Document.Sentences.Sentence.Dependencies.Dep.Governor createRootDocumentSentencesSentenceDependenciesDepGovernor() {
        return new Root.Document.Sentences.Sentence.Dependencies.Dep.Governor();
    }

    /**
     * Create an instance of {@link Root.Document.Sentences.Sentence.Dependencies.Dep.Dependent }
     * 
     */
    public Root.Document.Sentences.Sentence.Dependencies.Dep.Dependent createRootDocumentSentencesSentenceDependenciesDepDependent() {
        return new Root.Document.Sentences.Sentence.Dependencies.Dep.Dependent();
    }

    /**
     * Create an instance of {@link Root.Document.Sentences.Sentence.Tokens.Token }
     * 
     */
    public Root.Document.Sentences.Sentence.Tokens.Token createRootDocumentSentencesSentenceTokensToken() {
        return new Root.Document.Sentences.Sentence.Tokens.Token();
    }

}
